### ISSUE TITLE
OJP 2.0 LIR "Schulstr" + Restrictions.Type=address return stop entries

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#10]
https://tools.odpch.ch/ojp-api-explorer-v2/?gist=c6c323e032cef73db0448f93153da1af

<img height="400" alt="image" src="https://github.com/openTdataCH/ojp-sdk/assets/113994/a24d9098-8b39-4d99-b91a-e6b583c779bd">

```
<PlaceResult>
    <Place>
      <StopPlace>
        <StopPlaceRef>8577594</StopPlaceRef>
...
```

only `Address` should be expected

Request
`/POST https://api.opentransportdata.swiss/ojp20`
XML: https://gist.github.com/vasile/c6c323e032cef73db0448f93153da1af

**Comment by TO-mdv** [comment]
Bug created [SH-2854](https://youtrack.mentz.net/issue/SH-2854) OJP2.0 Adress Filter ohne Funktion -> LIR-2d_Address Filter

**Comment by TO-mdv** [comment]
address filter is now taking into account. But in the response are still missing elements like coordinates. We will fix that next week.
`<PlaceResult>
    <Place>
        <Name>
            <Text xml:lang="de">Schulstrasse (Oberhallau)</Text>
        </Name>
    </Place>
    <Complete>true</Complete>
    <Probability>1</Probability>
</PlaceResult>`

**Comment by TO-mdv** [comment]
The response is now fixed as well. Fix available on TEST, INT and PROD
