### ISSUE TITLE
Situations: `AlertCause` always `unknown` in `PTSituation`

### ISSUE THREAD

**Issue by r3to** [openTdataCH/ojp-sdk#103]
[Realisierungsvorgabe (RV) Profil CH SIRI-SX/VDV736](https://www.oev-info.ch/sites/default/files/2024-07/realization_guide_siri-sx_oev_schweiz_v1.0.pdf) defines following possible values:

<img width="1002" alt="image" src="https://github.com/user-attachments/assets/41e24701-7ac3-4efc-8b7c-95473aa3767a">

**Example:** 

`AlertCause` is defined as `constructionWork` in SIRI-SX but is returned as `unknown` in OJP Response

| SIRI-SX | OJP |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/2dee521e-6610-40a0-9989-20fcbe27272a) | <img width="916" alt="image" src="https://github.com/user-attachments/assets/6df03997-9c3a-41ce-a101-0cd30bd5e32b"> |

**Comment by knr2000** [comment]
Thank you for your enquiry.

We will check the findings in the coming weeks. Currently the AlertCause from SIRI-SX are not mapped to OJP.

**Comment by TO-mdv** [comment]
@r3to this is a new feature, we have that already on the board on first position in the backlog: #60 
Please close this issue, it's duplicate to the existing one

**Comment by r3to** [comment]
@TO-mdv ah, sorry, didn't see that. 

Closing as Duplicate from #60
