### ISSUE TITLE
TR: How should `Deviation` be handled?

### ISSUE THREAD

**Issue by r3to** [openTdataCH/ojp-sdk#105]
We get `Deviation` on two trips from "Bern – Brienz". One has the last leg with origin/destination `NotServiced` and the other one has no issues.

See example on [Gist](https://gist.github.com/r3to/3409ed84309f1d5160e575fbd6bfdad5)

![f779a8e1-32b9-4418-9d5a-c09ab759c2b6](https://github.com/user-attachments/assets/02e029d6-8474-4ade-b693-97833e44ede1)

![60d6a3c7-f21b-4064-aa5e-5a01cd0bfeeb](https://github.com/user-attachments/assets/1c8e2a33-f6f1-44d5-87d7-ed899f02920b)

should the second trip be treated as the "Deviation" of the first trip?

**Comment by r3to** [comment]
Relates to #41

**Comment by TO-mdv** [comment]
Gerade gecheckt mit aktuelle Beispiel. Auf der Linie S24 gibt es einen Zusatzhalt für Thayngen



![Image](https://github.com/user-attachments/assets/13aa777f-82a8-426c-a5ad-d888979897d5)



Der TripRequest von Schaffhausen nach Herblingen liefert nun das Flag "Deviation", da ein Teil der Linie S24 eine Umleitung ( =Zusatzhalt, welcher nicht in der Randspalte enthalten ist) hat. Die Fahrt wird damit in OJP2.0 korrekt als "Deviation" ausgegeben. Für den Moment macht der OJP also alles richtig, ob die Ausgabe so sinnvoll für den Fahrgast ist müssen wir in der Runde mit SBB besprechen.




![Image](https://github.com/user-attachments/assets/d9c2ae6e-ac25-43cf-bbca-b4136ef0e99f)

**Comment by r3to** [comment]
As `Deviation` is true on the `Trip` eventhough the devation doesn't affect the `TimedLeg`, we've decided to ignore this property for the time being.
