### ISSUE TITLE
Train is cancelled but should not be

### ISSUE THREAD

**Issue by terencebls** [openTdataCH/ojp-sdk#108]
![image](https://github.com/user-attachments/assets/fa7fe4c6-15ba-4c3d-96dd-9314c75e896f)
Those two trains are marked as cancelled, but if we check the SBB Timetable they are not cancelled:

![image](https://github.com/user-attachments/assets/4ed2cc9d-3d55-4010-b10f-f127b8e0d241)

Can you please have a look?

**Comment by TO-mdv** [comment]
[EFABA-3780](https://youtrack.mentz.net/issue/EFABA-3780) OJP 2.0 durchgebundene Fahrt fälschlicherweise "cancelled"

Bug intern erstellt. Das Problem scheint bei durchgebundenen Zügen zu bestehen, dass beim zweiten Teil der Fahrt (nach der Durchbindung) die Echtzeit nicht abgebildet werden kann und somit als cancelled markiert wird. Der Entwickler schaut sich das mit hoher Prio an.

**Comment by TO-mdv** [comment]
Aufgrund einer Sonderregel, die für die Echtzeit der grenzüberschreitenden Fahrten (bsp. Schaffhausen Herblingen) implementiert wurde, weisen nun Inlandfahrten mit Durchbindungen und getrennte Echtzeit für Teilstrecke 1 und 2 diese Ausfälle auf.

Dies führt schweizweit zu bis zu 29 Fahrtausfällen, die implizit generiert werden. 

Wir suchen weiterhin eine Lösung für das Problem.

**Comment by TO-mdv** [comment]
Problem resolved.

before (PROD):


![Image](https://github.com/user-attachments/assets/14b88494-6f29-40d4-a71a-4ac9a4d2ccbf)


![Image](https://github.com/user-attachments/assets/4600abd2-d4f0-48cd-a40a-b224acfa6fbe)




after (TEST/INT):


![Image](https://github.com/user-attachments/assets/893744f1-2d49-4f40-9f50-c20ba78b6d03)


![Image](https://github.com/user-attachments/assets/a77a589e-3e7b-4eab-8651-bdc448e8e899)

**Comment by terencebls** [comment]
ok
