### ISSUE TITLE
no platform for RBS trains

### ISSUE THREAD

**Issue by Flurin-BLS** [openTdataCH/ojp-sdk#113]
On Hafas we have the platform, on OJP it is missing...

https://tools.odpch.ch/ojp-demo-v2/search?from=8504194&to=8508068&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-08-28%2019:52&stage=v2-prod

![Image](https://github.com/user-attachments/assets/69d32704-3f57-4dfa-be47-38a05c3f0587)

![Image](https://github.com/user-attachments/assets/2432c121-ac87-4191-b730-8bc7bbdd9ee4)

**Comment by Flurin-BLS** [comment]
Hi @u233336 , since Andreas and Matthias are on holiday, I assign this Data-Quality Issue to you...

**Comment by u233336** [comment]
Maybe I don't get it right, but I don' see the platform info on Hafas either:

**OJP:**

![image](https://github.com/user-attachments/assets/5138b051-5e8a-4a77-96f7-bcb8764d26c5)


**Hafas (sbb.ch)**

![image](https://github.com/user-attachments/assets/ad8e7b42-fb64-482c-9eef-73b2ad07318f)


Second picture from Flurin's message (Bern --> Worblaufen), no platform on sbb.ch:

![image](https://github.com/user-attachments/assets/c37c7649-ebbc-4a70-96ab-683abee008ac)

**Comment by u233336** [comment]
So to me it looks like a data issue, not a bug in OJP

**Comment by Flurin-BLS** [comment]
hm... your right, the 21:39 doesn't have platform on hafas.. I checked an other time on hafas.. 


![Image](https://github.com/user-attachments/assets/43683731-9a6b-4454-82fb-1e54753bb7b5)

It seems that many RBS-Lines don't provide the platform... maybe because they don't have a fixed platform?
I close the ticket...

**Comment by Flurin-BLS** [comment]
Good Morning @u233336 - have to reopen this one... but maybe the "right" question is - who is in charge for the platform data from RBS?


![Image](https://github.com/user-attachments/assets/06b5ef2e-b4da-4026-b705-bb7df662e3fc)



![Image](https://github.com/user-attachments/assets/4a702213-cff1-4874-9a28-44c2bec99ba5)





![Image](https://github.com/user-attachments/assets/de6a2171-c15f-48a7-81c8-d1e7bc3758ab)
![Image](https://github.com/user-attachments/assets/d8b27f00-3c07-4c4b-a03d-fc8884475c89)

**Comment by u233336** [comment]
RBS itself is in charge for their data. They collect the data tehmselves and send them via railML to MENTZ and then to INFO+. 

For the moment I think all the platform information should be correct. But in fact RBS had a problem in the past. Could you please check again?

**Comment by Flurin-BLS** [comment]
Seems that the Trainline-Info are corrected now.. but the planed and estimated track is still not correct: 


![Image](https://github.com/user-attachments/assets/57e4f7a1-f86a-4f35-a17b-58be21b71d95)



![Image](https://github.com/user-attachments/assets/eb7ae8cd-110e-4767-8a9d-bf7aa56e6852)

**Comment by u233336** [comment]
Let's keep an eye on it, for the moment all the tracks are correct. I will check this again tomorrow morning:

![image](https://github.com/user-attachments/assets/7c55acd8-0d9b-43d8-8536-9a2ee47cec29)

**Comment by u233336** [comment]
This morning (07:30 am) it still looks good to me. I'll have a look at it again later today

**Comment by Flurin-BLS** [comment]
seems to be ok now
