### ISSUE TITLE
Wrong duration time if next leg has delay

### ISSUE THREAD

**Issue by michaelruppen** [openTdataCH/ojp-sdk#115]
Currently only occurred with ContinuousLeg (but maybe TransferLeg are affected too)

When requesting a trip which starts f.e. from an address to a Station: `Naters, Landstrasse 62 -> Bern` the first Leg is most of the times a continuousLeg from the address to Brig.
If the train in Brig has a delay, the duration on the ContinuousLeg get added the delay, see #[ response](https://gist.github.com/michaelruppen/1e5f8350697b12312eaa38937ba5d5e9)

Normally the duration for the ContinuousLeg for that is 18min (see last tripResult as reference). But the trip with `<Id>ID-8295BC37-17F4-42AA-B95E-F3A4B9754CA7</Id>` has 19min duration.
But the continuousLeg duration should not change, even if the next timedLeg has a delay

Testen on TEST and INT environment

**Comment by TO-mdv** [comment]
most likely same problem as https://github.com/openTdataCH/ojp-sdk/issues/109

**Comment by TO-mdv** [comment]
[SH-3527](https://youtrack.mentz.net/issue/SH-3527) OJP2.0 TR erklärende Echtzeit - unnötiges "Infeasible"

**Comment by TO-mdv** [comment]
development on-going, should be fixed by this week and ready for golive by 22.9.2024

**Comment by terencebls** [comment]
is solved.
