### ISSUE TITLE
Trip should be marked as cancelled but is not

### ISSUE THREAD

**Issue by terencebls** [openTdataCH/ojp-sdk#116]
The connection Bern - Solothurn has a cancellation.

But OJP returns not the connection as cancelled, even if the starting station "Bern" is cancelled.

<img width="390" alt="image" src="https://github.com/user-attachments/assets/27ee9cb1-e457-479e-9afc-0ea7350ff3fe">

Request:

`<OJP version="2.0" xmlns="http://www.vdv.de/ojp" xmlns:siri="http://www.siri.org.uk/siri" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <OJPRequest>
        <siri:ServiceRequest>
            <siri:RequestTimestamp>2024-08-29T15:13:22Z</siri:RequestTimestamp>
            <siri:RequestorRef>OJP_Demo_iOS_IOS_SDK_0.1.0</siri:RequestorRef>
            <OJPTripRequest>
                <siri:RequestTimestamp>2024-08-29T15:13:22Z</siri:RequestTimestamp>
                <Origin>
                    <PlaceRef>
                        <StopPlaceRef>8507000</StopPlaceRef>
                        <Name>
                            <Text>Bern</Text>
                        </Name>
                    </PlaceRef>
                    <DepArrTime>2024-08-29T15:13:22Z</DepArrTime>
                </Origin>
                <Destination>
                    <PlaceRef>
                        <StopPlaceRef>8500207</StopPlaceRef>
                        <Name>
                            <Text>Solothurn</Text>
                        </Name>
                    </PlaceRef>
                </Destination>
                <Params>
                    <NumberOfResults>6</NumberOfResults>
                    <IncludeIntermediateStops>true</IncludeIntermediateStops>
                    <UseRealtimeData>explanatory</UseRealtimeData>
                </Params>
            </OJPTripRequest>
        </siri:ServiceRequest>
    </OJPRequest>
</OJP>`

Response: 

https://gist.github.com/terencebls/cd5d11fb444c51f31752b194b96f5cc0

**Comment by TO-mdv** [comment]
issue not resolved yet, create another bug: [SH-3559](https://youtrack.mentz.net/issue/SH-3559) OJP2.0 TR erklärende Echtzeit - Trip sollte cancelled sein, da erster Stop notServiced

**Comment by TO-mdv** [comment]
after today's session about "erklärende Echtzeit", this issue should be resolved.

**Comment by terencebls** [comment]
Work as designed
