### ISSUE TITLE
plannedQuay has no platform data

### ISSUE THREAD

**Issue by terencebls** [openTdataCH/ojp-sdk#118]
From EstimatedQuay we get the platform number, and sometimes also the sector (example: Bern - Murten).

But for the same trip, in the PlannedQuay field there are never the sector, so this is always handled as a platform change, even if it's not the case.

**Comment by terencebls** [comment]
![image](https://github.com/user-attachments/assets/728abfaf-fb1c-4b45-bc92-7126db179fa6)

**Comment by u233336** [comment]
All the data seem to be correct in our systems, but the planned quay doesn't respect the sector. Inquiry with MENTZ is ongoing

**Comment by TO-mdv** [comment]
crreated bug for datacollection system: [DIVA-16372](https://youtrack.mentz.net/issue/DIVA-16372) Sektor-scharfe HRDF-Fahrten starten ab Steig ohne Sektor

**Comment by TO-mdv** [comment]
Bug fixed on TEST. Released on PROD at 30.9.2024

![Image](https://github.com/user-attachments/assets/db449fcd-4351-4d08-97f6-d9e1c35cf0aa)

**Comment by terencebls** [comment]
fixed
