### ISSUE TITLE
TimedLeg is notServicedStop=true but trip is not cancelled

### ISSUE THREAD

**Issue by michaelruppen** [openTdataCH/ojp-sdk#119]
The trip has LegBoard and LegAlight of firstTimedLeg marked as notServicedStop=true. The trip itself is only marked as "deviation=true", but when the first TimedLeg can't be used, shouldn't be the trip marked as cancelled?

Data [Gist](https://gist.github.com/michaelruppen/cbec1746324b67114e873fd06282ddff) 
TripId: ID-F82F73D0-0B2B-4BE9-88C0-8DE2DD0C5D6A

**Comment by TO-mdv** [comment]
Aus unserer Sicht ist nach dem Gespräche Session erklärende Echtzeit das Theme besprochen. Der OJP2.0 macht im Moment alles korrekt

**Comment by r3to** [comment]
See #126 

- `TripStatus.Cancelled` will be removed.
- `ServiceStatus.Cancelled` will be implemented, but only set to `true` if the whole service is cancelled and not parts of it.
