### ISSUE TITLE
LIR "Bern" + no Restrictions throws an error

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#12]
https://tools.odpch.ch/ojp-api-explorer-v2/?gist=2c6e30bc3a368797891f8f2a18656d4c

### 1st problem 
The `<Restrictions>` is optional according to XSD schema, with OJP v1.0 works
https://vdvde.github.io/OJP/develop/index.html#OJPLocationInformationRequestStructure

### 2nd problem 
Error returned is JSON type

```
{
    "traceId": "36c60561-5ac9-4de3-aede-8620a9497be1",
    "error": "Object reference not set to an instance of an object.",
    "host": "ODP-EC2-SHLNX01-P"
}
```

Request
`/POST https://api.opentransportdata.swiss/ojp20`
XML: https://gist.github.com/vasile/2c6e30bc3a368797891f8f2a18656d4c

**Comment by vasile** [comment]
related with #20

**Comment by TO-mdv** [comment]
Release 12.8.2024 (32-stable)

**Comment by vasile** [comment]
Works as expected, closing
