### ISSUE TITLE
Replacement train not present 

### ISSUE THREAD

**Issue by terencebls** [openTdataCH/ojp-sdk#120]
Today at 07:34 between Fribourg and Bern there was a cancelled train.

But another train was present (Ersatzzug) and made the trip.
OJP shows only the cancelled train, but not the replacement train:

<img width="689" alt="image" src="https://github.com/user-attachments/assets/3ebe238a-922e-48f4-b7ed-984892dcebb1">

The reality was like here:

<img width="583" alt="image" src="https://github.com/user-attachments/assets/34a03994-fcb9-40e1-b1f5-5e91981918b7">

**Comment by TO-mdv** [comment]
also found an example where in ojp the replacement train is correctly marked as "cancelled" and the replacement train correct as "unplanned". But at sbb.ch, the information about the replacement is missing:
![Image](https://github.com/user-attachments/assets/a28e511b-50e1-477e-8baf-a365d9350448)

Probably, sbb.ch does some changes in the realtime messages

**Comment by TO-mdv** [comment]
one more working example:
![Image](https://github.com/user-attachments/assets/dc97fd89-3c13-4247-a463-e5e958d27fb6)
![Image](https://github.com/user-attachments/assets/a6016057-a049-4484-8426-e0dad9441442)

**Comment by TO-mdv** [comment]
one more working example, but without replacement train (only cancelled) in both systems:
![image](https://github.com/user-attachments/assets/d47123b5-31e0-45b7-aa3c-cb94507a6ef0)
![image](https://github.com/user-attachments/assets/97b84531-47cc-44b4-b19d-90cfadaa47db)

**Comment by r3to** [comment]
Removing blocker, as we didn't find an example to reproduce

**Comment by terencebls** [comment]
not reproducible
