### ISSUE TITLE
Situations do not match trip & leg data

### ISSUE THREAD

**Issue by michaelruppen** [openTdataCH/ojp-sdk#121]
Given this [Gist](https://gist.github.com/michaelruppen/ef4c00059b6b374ed2c72613843b0e2a) there are 2 issues, where the data of the situations do not match trip & leg data.

1. The station "Oberhofen am Thunersee" is closed, but the intermediateStop does not have "notServicedStop=true"
2. The service is interrupted because of an issue, but the trip is not marked as cancelled=true

SituationNumbers:
- ems-2423
- ems-2417

Possible TripId: ID-E63E338E-3830-4DBF-8F56-CA1393D67112

**Comment by TO-mdv** [comment]
hi @michaelruppen 
Ich habe mit den Leuten vom EMS gesprochen und die Störungsmeldung zurückverfolgt.
Aktuell kann das EMS keine routBlocking oder stopBlocking Meldungen ausgeben. Also alle Meldungen vom EMS haben nur informativen Charakter und wirken sich nicht in der Echtzeit (notServicedStop, Cancelled) aus.
Hast du noch Fragen dazu? Sonst würde ich dann das Ticket nächste Woche schliessen.
Bon weekend!

**Comment by michaelruppen** [comment]
Hey @TO-mdv 
Also das bedeutet, wir können EMS bezogen Meldungen dann zwar über die Echtzeit darstellen (also die Meldung/Situation), aber wir können nicht in den Details darstellen, dass eben genau dieser eine Stop (oder mehrere) gar nicht bedient werden (also auf der View wo der Stop dargestellt wird, ausser wir würden ein String matching versuchen).
und was bedeutet aktuell, ist da in Zukunft eine Änderung am EMS-System vorgesehen?

Aber ja stand jetzt können wir ja dementsprechend nichts anderes tun, also würde ich das Ticket auch schliessen, aber evtl. ein Feature Ticket verlinken, wenn es eine Änderung am System geben wird.
Schönes weekend!🌞

**Comment by TO-mdv** [comment]
Richtig. Viele TU's senden via Echtzeit VDV454 jeweils noch den Fahrtausfall oder eine nicht bediente Haltestellen und verwenden das EMS nur für Meldungen, warum etwas ausfällt oder nicht bedient ist.

Wann das im EMS geplant ist, kann ich nicht sagen.

**Comment by r3to** [comment]
closing, as Thomas has moved it to Done
