### ISSUE TITLE
Intermediate stops are 37 instead of 42 for this connection

### ISSUE THREAD

**Issue by terencebls** [openTdataCH/ojp-sdk#124]
For this connection (Marin Epagnier - Cormondreche Grand Rue at 19:06)  we get 37 intermediate stops.
<img width="625" alt="image" src="https://github.com/user-attachments/assets/a511513f-4e28-405e-a8d9-f60dbbb73f42">

But on Hafas or sbb.ch we get 42.

<img width="606" alt="image" src="https://github.com/user-attachments/assets/08e653ba-9f94-4ae1-ae0b-10f88e33ca0e">

Can you please have a look?

Best regards.

**Comment by TO-mdv** [comment]
@terencebls I checked the connection for 14.10. and 21.10. and compared to sbb.ch and Hafas. There were all identical. Did you do send the request mit date = today or for the future?

If for today, it might be that the VDV454-REFAUS or AUS data had an impact.

![Image](https://github.com/user-attachments/assets/a74e3ac5-3799-486e-ba7f-f8a3774d25a8)

**Comment by TO-mdv** [comment]
kein Feedback mehr erhalten, wird werden den Issue heute schliessen
