### ISSUE TITLE
LIR: Thun is not found (in French)

### ISSUE THREAD

**Issue by terencebls** [openTdataCH/ojp-sdk#136]
If you make a LIR Search in French for Thun, we receive a lot of Results in Thun, but not the main station of Thun.

Example of the request:

https://gist.github.com/terencebls/54e128ab3b47029d7e266ba83ae71689

Response:

https://gist.github.com/terencebls/09f8b9c2d8fb94ac0b5d1305ae60e43f

**Comment by TO-mdv** [comment]
@terencebls that's  because there is a different name in french and english for thun:
![Image](https://github.com/user-attachments/assets/d3592538-d775-41fd-84fa-27afa624cf68)

**Comment by terencebls** [comment]
But for some stations it works with both. Like in German you can search for Genève and you get the result.

**Comment by TO-mdv** [comment]
Zu diskutieren, wie wir mit fremdsprachigen Namen umgehen und ausgeben.

**Comment by TO-mdv** [comment]
@AndreasAtSBB Hier die Liste mit allen Haltestellen, die einen französischsprachigen Haltestellennamen haben: [OJP Haltestellennamen mehrsprachig](https://docs.google.com/spreadsheets/d/1AdjD2YelrRC_LSakQJGdMcXkeyYuNfF1_1ttq-8HfFI/edit?usp=sharing)

@terencebls Aus meiner Sicht könnt ihr den LIR mit Sprachangabe De stellen, dann sehe ich keine Nachteile.

**Comment by TO-mdv** [comment]
Noch weitere Beispiele gefunden, die angepasst werden:
Laufen		Laufon
Grenchen Süd	Granges (SO) sud
Bettlach		Bâche
Selzach		Saucy

**Comment by TO-mdv** [comment]
Dieser Fall mit Thun ist allerdings behoben

**Comment by TO-mdv** [comment]
Weitere Fälle gemäss Liste nach Absrpache mit @u233336 angepasst: https://sbb-my.sharepoint.com/:x:/g/personal/christoph_lucas_sbb_ch/EWxj0QpQj39OqU9LvnRi7PkB5tTOVZ79NwuN5PV9pzCDcQ?email=odermatt%40mentz.net&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1732086724089&web=1

Go-live mit nächster Datenaufbereitung am Donnerstag.
