### ISSUE TITLE
Trip marked as infeasible, but should be feasable

### ISSUE THREAD

**Issue by terencebls** [openTdataCH/ojp-sdk#144]
This trip was marked as infeasible:

![image](https://github.com/user-attachments/assets/01bb7dcb-695b-4682-9ee8-a94377a1c7dd)

But when we look at the change times and the delays, there is enough time to change.

Here is the xml response: https://gist.github.com/terencebls/a5d55574cdf94b5b741089c1a6637c38

Why is this trip marked as infeasible?

**Comment by TO-mdv** [comment]
already fixed on TEST with Ticket [SH-4214](https://youtrack.mentz.net/issue/SH-4214) OJP2.0 TR Trip wird als "Infeasible" gekennzeichnet, obwohl erreichbar
