### ISSUE TITLE
Train missing S44 Thun - Solothurn

### ISSUE THREAD

**Issue by Flurin-BLS** [openTdataCH/ojp-sdk#146]
The train S44 from Thun - Solothurn is not shown in the results.

The trip 13:08 without transfer and only 14 minutes more travel time should also be shown in the results.

https://tools.odpch.ch/ojp-demo-v2/search?from=8507100&to=8500207&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-10-22%2013:00&stage=v2-prod

![Image](https://github.com/user-attachments/assets/33aff529-fe3f-49d5-b3ae-10f0f8796541)

![Image](https://github.com/user-attachments/assets/f41355bd-165f-4fa5-abd7-0b70481c5011)

**Comment by u233336** [comment]
Gehört zum "Problem" früher-einsteigen-und-später-ankommen.
Wird mit den direkten Verbindungen jedoch gelöst sein (PI 21), denn auf OJP 1.0 erscheint die Verbindung um 13:08 Uhr immer und dort sind die direkten Verbindungen bereits umgesetzt.
https://opentdatach.github.io/ojp-demo-app/search?from=8507100&to=8500207&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-10-22%2013:00&stage=prod
