### ISSUE TITLE
Doppelte Fahrten bei erklärender Echtzeit

### ISSUE THREAD

**Issue by TO-mdv** [openTdataCH/ojp-sdk#158]
Bei erklärender Echtzeit und Abweichung von Gleisen werden Fahrten fälschlicherweise doppelt ausgegeben.

![Image](https://github.com/user-attachments/assets/3e295842-e6a0-405d-8cb7-8d6cc16a6727)

![Image](https://github.com/user-attachments/assets/208fd3b8-b4cb-4593-b78b-0fff4d73c8e0)

**Comment by r3to** [comment]
@TO-mdv ist das jetzt auf INT? scheint immer doppelte Fahrten anzugeben (vorher getestet mit Thun – Kandersteg)

**Comment by AndreasAtSBB** [comment]
Wenn man nicht "explanatory" anfragt werden die Fahrten zwar nicht doppelt angezeigt, aber die Fahrt welche durch die AUS-Meldungen entstand und den Umstieg enthält wird neu angezeigt. Somit ist dieser Fehler noch bestehend: Hier der Smoke-Test auf INT:
![Image](https://github.com/user-attachments/assets/21c8e833-ac14-4171-bce5-d8e7ea4a1ca2)
Mit explanatory werden die Fahrten auf INT nach wie vor doppelt angezeigt.

Ergo, ohne explanatory wird die falsche Fahrt ausgegeben und mit, immer noch doppelte Fahrten, somit bitte nicht Publizieren, weil keine Verbesserung!

**Comment by TO-mdv** [comment]
@AndreasAtSBB Das ist ein anderes Problem bei durchgebundenen Fahrten, welches wir in diesem Ticket verfolgen: https://github.com/openTdataCH/ojp-sdk/issues/157

Bitte kläre mit @u233336, ob ihr diese Version aus INT heute liveschalten möchtet oder nicht.

**Comment by AndreasAtSBB** [comment]
Stimmt ist der andere Bug, hier passt es scheinbar, somit kann dies released werden.

**Comment by TO-mdv** [comment]
Alles klar, danke!
