### ISSUE TITLE
Busverbindungen werden nicht angzeigt

### ISSUE THREAD

**Issue by Flurin-BLS** [openTdataCH/ojp-sdk#164]
Wir haben Kudenrückmeldungen das Ticket nicht mehr über BLS-Mobil gekauft werden können. Die gewünschte Verbindung wird über OJO nicht angeboten - es werden KEINE Verbinundgen angeboten.

https://tools.odpch.ch/ojp-demo-v2/search?from=8588628&to=46.941780,7.784670(Langnau%20im%20Emmental)&stage=v2-test

![Image](https://github.com/user-attachments/assets/6d04125e-48ac-49bd-857b-8bd773075204)

![Image](https://github.com/user-attachments/assets/85135a53-6ab8-4c10-9894-7d6c918998f6)

**Comment by u233336** [comment]
Meine Anfrage für morgen Dienstag ergibt eine lupenreine und mit sbb.ch identische Antwort:

<img width="653" alt="image" src="https://github.com/user-attachments/assets/1b6cb594-2c33-4340-8fd5-c92e73dca7ee">

**Comment by u233336** [comment]
Aus meiner Sicht kein Bug.

**Comment by Flurin-BLS** [comment]
Ja der Bug scheint behoben.. :-) wisst ihr was das Problem war?

**Comment by u233336** [comment]
Bin nicht sicher, ob das jemals ein Bug war. Ist nicht nachvollziehbar.

**Comment by Flurin-BLS** [comment]
war definitiv einer... habe aber leider vergessen auch ein Screenshot statt nur ein Permalink von OJP Demo einzufügen. ABer ist das Gleiche Problem wie hier: https://github.com/openTdataCH/ojp-sdk/issues/162 da hatte es Screenshots

**Comment by u233336** [comment]
Ja, das war ein Bug. Ein entsprechendes Ticket wurde bei MENTZ eröffnet. Bin gerade am abklären...
