### ISSUE TITLE
LIR Name search with "Bern S" and Type=address doesnt return any results

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#18]
https://tools.odpch.ch/ojp-api-explorer-v2/?gist=d0a5a4970e9bf2efb924a55e662b7a89

```
<OJP xmlns:siri="http://www.siri.org.uk/siri" xmlns="http://www.vdv.de/ojp" version="2.0">
  <OJPResponse>
    <siri:ServiceDelivery>
      <siri:ResponseTimestamp>2024-05-06T14:33:07.3954116+00:00</siri:ResponseTimestamp>
      <siri:ProducerRef>MENTZ</siri:ProducerRef>
      <OJPLocationInformationDelivery>
        <siri:ResponseTimestamp>2024-05-06T14:33:07.3954136+00:00</siri:ResponseTimestamp>
        <siri:RequestMessageRef>627f8705-b9e0-431b-9296-92e32165c119</siri:RequestMessageRef>
        <siri:DefaultLanguage>de</siri:DefaultLanguage>
        <CalcTime>1</CalcTime>
      </OJPLocationInformationDelivery>
    </siri:ServiceDelivery>
  </OJPResponse>
</OJP>
```

Request
`/POST https://api.opentransportdata.swiss/ojp20`
XML: https://gist.github.com/vasile/d0a5a4970e9bf2efb924a55e662b7a89

**Comment by TO-mdv** [comment]
I'm currently trying a new configuration to search already for 1 ngram like "S". Test on-going, keep you up to date in this ticket

**Comment by TO-mdv** [comment]
Same result as before:
![image](https://github.com/openTdataCH/ojp-sdk/assets/72090402/45f9542a-e647-4db5-bfbb-7883f66076eb)

We will work on that in feature SKI-1651

**Comment by TO-mdv** [comment]
Bug created [EFABA-3460](https://youtrack.mentz.net/issue/EFABA-3460) OJP2.0 Keine Ergebnisse für StopFinder suche "Bern S" street/address

**Comment by TO-mdv** [comment]
Resolved on INT
Release PROD 29.5.2024


![Image](https://github.com/openTdataCH/ojp-sdk/assets/72090402/cb26c0cd-aa0a-494a-96dd-53f3e86dd8d0)
