### ISSUE TITLE
How To / Links

### ISSUE THREAD

**Issue by TO-mdv** [openTdataCH/ojp-sdk#193]
- [Meetings](https://github.com/openTdataCH/ojp-sdk/wiki/Meeting-and-process-for-OJP-SDK-development#meetings)
- [Process](https://github.com/openTdataCH/ojp-sdk/wiki/Meeting-and-process-for-OJP-SDK-development#process)
- [Issue handling](https://github.com/openTdataCH/ojp-sdk/wiki/Meeting-and-process-for-OJP-SDK-development#issue-handling)

**Comment by TO-mdv** [comment]
@Flurin-BLS Was ist damit? Du hast das mal als Draft erstellt, wenn nicht mehr benötigt bitte schliessen.

**Comment by Flurin-BLS** [comment]
Merci für den Hinweis @TO-mdv  - keine Ahnung, was ich da machen wollte :-) ist geschlossen
