### ISSUE TITLE
LIR should conform to XSD

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#20]
Follow up from https://github.com/openTdataCH/ojp-sdk/issues/6

OJP 2.0 LIR request returns `<Place>` entries without `<GeoPosition>` or `<Name>` which is breaking the XSD schema
https://vdvde.github.io/OJP/develop/index.html#PlaceStructure

Example request / response

https://gist.github.com/vasile/cce1de006e0c4b910bcea106672bfbb5#file-ojp_geoposition_issue-xml-L40-L50

```
<Place>
  <TopographicPlace>
    <TopographicPlaceCode>23016216:1</TopographicPlaceCode>
    <TopographicPlaceName>
      <Text xml:lang="de">Hof (Rorschacherberg)</Text>
    </TopographicPlaceName>
  </TopographicPlace>
  <Name>
    <Text xml:lang="de">Hof (Rorschacherberg)</Text>
  </Name>
</Place>
```

**Comment by vasile** [comment]
@TO-mdv  OJP 2.0 LIR response should not return such entries
- either they should be discarded from the response
- or to be discarded at the import time

**Comment by vasile** [comment]
@TO-mdv - please follow-up with a resolution plan here

**Comment by TO-mdv** [comment]
Remove Stops without Coordinates, TO create Story

**Comment by TO-mdv** [comment]
[SH-2978](https://youtrack.mentz.net/issue/SH-2978) OJP2.0 LIR Objekte ohne Koordinaten herausfiltern -> LIR-1j_SP_LocationName_keine Koordianten

**Comment by TO-mdv** [comment]
Released on INT
Release PROD 29.5.2024
