### ISSUE TITLE
TR - need an example GeoPosition to StopRef and GeoPosition to GeoPosition

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#24]
Using this example for now on

```
<OJP xmlns:siri="http://www.siri.org.uk/siri" version="2.0"
  xmlns="http://www.vdv.de/ojp"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <OJPRequest>
    <siri:ServiceRequest>
      <siri:RequestTimestamp>2024-01-16T11:26:01.697Z</siri:RequestTimestamp>
      <siri:RequestorRef>OJP_SDK_v0.9.24</siri:RequestorRef>
      <OJPTripRequest>
        <siri:RequestTimestamp>2024-01-16T11:26:01.697Z</siri:RequestTimestamp>
        <Origin>
          <PlaceRef>
            <GeoPosition>
              <siri:Longitude>8.567587</siri:Longitude>
              <siri:Latitude>47.773983</siri:Latitude>
            </GeoPosition>
            <Name>
              <Text>Hagenturm</Text>
            </Name>
          </PlaceRef>
          <DepArrTime>2024-05-21T16:10:00.373Z</DepArrTime>
        </Origin>
        <Destination>
          <PlaceRef>
            <StopPlaceRef>8505069</StopPlaceRef>
            <Name>
              <Text>Rigi Kulm</Text>
            </Name>
          </PlaceRef>
        </Destination>
        <Params>
          <NumberOfResultsBefore>0</NumberOfResultsBefore>
          <NumberOfResultsAfter>5</NumberOfResultsAfter>
          <IncludeTrackSections>true</IncludeTrackSections>
          <IncludeLegProjection>false</IncludeLegProjection>
          <IncludeTurnDescription>true</IncludeTurnDescription>
          <IncludeIntermediateStops>true</IncludeIntermediateStops>
        </Params>
      </OJPTripRequest>
    </siri:ServiceRequest>
  </OJPRequest>
</OJP>
```

**Comment by TO-mdv** [comment]
TR using GeoPosition is not working yet, need to fix this. Story created [SH-2971](https://youtrack.mentz.net/issue/SH-2971) OJP2.0 TR mit GeoPosition -> TR-3a GeoPosition

**Comment by TO-mdv** [comment]
Testfall nochmals zu prüfen

**Comment by TO-mdv** [comment]
Umkreissuche funktioniert, Fussweg erste/letzte Meile noch zu implementieren

**Comment by Flurin-BLS** [comment]
Gemäss Info von @TO-mdv ist der Fussweg LEG auf INT ab dem 8. Juli verfügbar - also rechtzeitig zu unserem Sprintstart

**Comment by TO-mdv** [comment]
Testing aufwändiger, wir müssen jede Response 1:1 vergleichen nach den Anpasungen.

**Comment by TO-mdv** [comment]
Update: es steht eine neue Version zum testen bereit, in einem eigenen Enwicklungsbranch. Aktuell teste ich erklärende Echtzeit, sobald dies durch ist werde ich dieses Ticket testen können. Bis Ende dieser Woche gibt es sicher ein Feedback.

**Comment by TO-mdv** [comment]
Testing läuft:

1) Fusswegrouting von GeoPosition nach GeoPosition erste Meile Bern
[Demo](https://tools.odpch.ch/ojp-demo-v2/search?from=46.944833,7.440443&to=8507150&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-07-25%2007:52&stage=v2-test)
![Image](https://github.com/user-attachments/assets/52ed3f18-8eef-4388-b4e5-87cee57f8703)

2) Fusswegrouting  von GeoPosition nach GeoPosition letzte Meile Zürich
[Demo](https://tools.odpch.ch/ojp-demo-v2/search?from=47.376835,8.539066&to=47.360890,8.521360(Staffelstrasse%20(Z%C3%BCrich))&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-07-25%2007:52&stage=v2-test) 
![Image](https://github.com/user-attachments/assets/6ccd9bb0-8c0f-4bcb-8f53-06c4d833cb53)

3) Fusswegrouting  von StopPointRef nach GeoPosition -> fehlerhaft, Fussweg wird nicht georeferenziert
[Demo](https://tools.odpch.ch/ojp-demo-v2/search?from=8503000&to=47.360890,8.521360(Staffelstrasse%20(Z%C3%BCrich)&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-07-25%2007:52&stage=v2-test)
![Image](https://github.com/user-attachments/assets/3416b42f-9bc8-434f-b397-b869cd9303a4)

4) Fusswegrouting  von GeoPosition nach StopPointRef -> fehlerhaft, Error
[Demo](https://tools.odpch.ch/ojp-demo-v2/search?from=46.758383,7.629729&to=8507492&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-07-25%2007:52&stage=v2-test)
![Image](https://github.com/user-attachments/assets/ecab2f2a-4997-41c4-a690-904f27c50e1b)

**Comment by TO-mdv** [comment]
Fehler 1) und 4) sind behoben auf INT. Fehler 2) und 3) ist ein anderes Programm betroffen, der zuständige Entwickler schaut sich das demnächst an.

**Comment by TO-mdv** [comment]
Release 12.8.2024 (32-stable)

**Comment by terencebls** [comment]
![image](https://github.com/user-attachments/assets/ceb07fe2-826c-4a09-9777-479e052c7de1)

@TO-mdv I currently see an issue, the Name should contains the Address where do you start, not the coordinates (for that we have already the coordinates in the GeoPosition.
