### ISSUE TITLE
LIR check missing housenumbers "Via Serafino Balestra 33 6900 Lugano"

### ISSUE THREAD

**Issue by TO-mdv** [openTdataCH/ojp-sdk#30]
a LIR for Via Serafino Balestra 33 6900 Lugano don't provide a valid housenumber.

LIR for "Staffelstrasse 12 8045" are working, seems to be a problem in the base data for addresses.

`<?xml version="1.0" encoding="utf-8"?>
<OJP xmlns="http://www.vdv.de/ojp" xmlns:siri="http://www.siri.org.uk/siri" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://www.vdv.de/ojp" version="2.0">
  <OJPRequest>
    <siri:ServiceRequest>
      <siri:RequestTimestamp>2024-05-23T10:05:24.717Z</siri:RequestTimestamp>
      <siri:RequestorRef>OJP_JS_SDK_v0.9.32</siri:RequestorRef>
      <OJPLocationInformationRequest>
        <siri:RequestTimestamp>2024-05-23T10:05:24.717Z</siri:RequestTimestamp>
        <InitialInput>
          <Name>Via Serafino Balestra 33 6900 Lugano</Name>
        </InitialInput>
        <Restrictions>
          <NumberOfResults>10</NumberOfResults>
        </Restrictions>
        <siri:Extensions>
          <ParamsExtension>
            <PrivateModeFilter>
              <Exclude>false</Exclude>
            </PrivateModeFilter>
          </ParamsExtension>
        </siri:Extensions>
      </OJPLocationInformationRequest>
    </siri:ServiceRequest>
  </OJPRequest>
</OJP>`

**Comment by TO-mdv** [comment]
I updated the address database, create a new GIS and prepare so new data's, to check if the address then appears

**Comment by TO-mdv** [comment]
check Adress data, found street Via Serafino Balestra in D:\ImportScripts\Layer_Kunden\Schweiz\StrTab_SingleHouse\23020192.StrTab

`atr;MPC;StreetID;StreetName;Origin;HasLink;IgnoreStreet`
`rec;23020192;1500000132;"Via Serafino Balestra";G;false;false`

also found the street in the official register in eingang_entree_entrata.csv
`400010762	0	101613380	33	10128208	Via Serafino Balestra	Via Serafino Balestra	Bal	9904	1	6900	0	Lugano			1	2024-05-28`

**Comment by TO-mdv** [comment]
Probably, it's because the missing postcode/city for this streets:
![Image](https://github.com/openTdataCH/ojp-sdk/assets/72090402/802f1839-372f-47ea-856e-369cf3d5d87b)


I try now to create new GIS data with added postcode/city for housenumber 33 and 31:
![Image](https://github.com/openTdataCH/ojp-sdk/assets/72090402/1d430509-3a4f-41c2-ab99-6228cd076338)

**Comment by r3to** [comment]
<img width="737" alt="image" src="https://github.com/openTdataCH/ojp-sdk/assets/105666/f0eb5015-fcdb-4186-a647-0be5cd6d9796">

@TO-mdv «Via Luigi Canonica» has a zip, but is also missing in the response. (Tested on Int and Test)

https://gist.github.com/r3to/d331c54ba84d275f18dc8a8911462980

**Comment by TO-mdv** [comment]
@r3to yes, you are right. I need to check that again

**Comment by TO-mdv** [comment]
the example of Via Luigi Canonica 8 is strange as well, there is a countrycode IT italy:


![Image](https://github.com/openTdataCH/ojp-sdk/assets/72090402/dac33ff7-fb67-4c90-adff-e8fef252903b)

**Comment by r3to** [comment]
ah, but i just took the «Via Luigi Canonica» in Lugano (just randomly looked at an other address near Via Balestra). Lissone actually in Italy ;-)

**Comment by Flurin-BLS** [comment]
Hey @TO-mdv - gibt's schon News vom GIS-Team? Ich verabschiede mich ins Wochenende und bin gespannt wie es am Montag aussieht.. LG

**Comment by TO-mdv** [comment]
hi @Flurin-BLS 
Unser GIS Team hat sich das wie versprochen angeschaut. Nun scheint aber ein Problem beim Script vorzuliegen, somit werden neue Adressen nicht aktualisiert.
Ich habe am Montag einen Termin, um nochmals zu prüfen bis wann der Entwickler das fixen kann.
Realistisch gesehen, wird das jedoch nochmals zwei Wochen dauern :-(
Sorry, dass ich da keine besseren News habe. Ich werde euch am Montag Nachmittag am Mobile Sync nochmals ein Update dazu geben.
Bon weekend trotzdem!

**Comment by TO-mdv** [comment]
Fix des Scriptes ist geplant bis 28. Juni 2024. Danach müssen die GIS Daten nochmals neu aufbereitet werden, somit sollten die Adressen auf PROD am 2. Juli zur Verfügung stehen.

**Comment by TO-mdv** [comment]
Das Script konnte gefixt werden. Wir haben neu 3'099'999 Adressen im OJP GIS (Vorher 2'299'999). Es sind keine Duplikate vorhanden und auch das Beispiel Via Serafino Balestra 33 ist enthalten, offensichtlich haben aber einige mehr gefehlt.

Ich bin gerade dabei, ein neues GIS zu erstellen. Wenn alles gut läuft, können wir am Montag, 1. Juli die neuen GIS Daten live schalten.

**Comment by Flurin-BLS** [comment]
Das klingt sehr gut! Und spannendes Mengengerüst... Haben also fast 1/3 der Adressen gefehlt.
________________________________

**Comment by TO-mdv** [comment]
Die Adressen sind korrekt im GIS. Nun gehen uns noch 800'000 Adressen beim Importieren in die EFA selber verloren. Dies haben wir soeben festegestellt und sind mit Hochdruck an der Lösung des Problems.

**Comment by TO-mdv** [comment]
das neue GIS mit geänderter Adressdaten Quelle ist nun auf INT verfügbar. Damit kommt ENDLICH die gewünschte Adresse, ich prüfe gleich noch das Mengengerüst, bin aber zuversichtlich dass nun alles da ist:


![Image](https://github.com/openTdataCH/ojp-sdk/assets/72090402/d22ba90a-14ea-42d4-9553-393eed42bfc6)

**Comment by TO-mdv** [comment]
Das Mengengerüst stimmt auch: Quelldaten 
3,17 Mio Adressen, in der EFA sind 3,02

**Comment by Flurin-BLS** [comment]
Ciao @TO-mdv , das sind erfreuliche News! Was passiert mit den 150'000 Adressen die nicht in EFA landen?
Wir starten in den nächsten Tagen die Abnahme von unserem Feature Stationssuche, werden das voraussichtlich am 5. August live schalten.
Wann ist euer Go-Live mit den Daten auf PROD? Danke und LG Flurin

**Comment by TO-mdv** [comment]
hi @Flurin-BLS 
Ich habe einige Fälle von diesen 150k analysiert.

`Rue Pierre-Beau 17.1 2015 Areuse` wir haben nur die Nummer 17, wir können nicht 17.1. Davon hat es 20'000 Fälle
`Ober Ebnet--6463` Bei Adressen benötigen wir immer eine Hausnummer, einige haben keine. Davon hat es 20'000 Fälle
`Ruelle de la Croix Blanche-4a-1976` für die restlichen Fälle 110k habe ich noch keine Erklärung, da bin ich noch dran.

**Comment by Flurin-BLS** [comment]
Merci für die Info! Ja solche Spezialfälle wird es wohl noch mehr geben... wir haben nun auf jeden Fall ein Mengengerüst wo wir ohne Problem live gehen können.
Wie sind eure Releasezyklen noch einmal? Sind die auf SBB-Confluence dokumentiert? Würde hier gerne noch eure PROD-Termin kommunizieren... Danke und LG

**Comment by vasile** [comment]
fixed on INT / TEST
