### ISSUE TITLE
TR: Multiple occurrences of the same trip in a TripRequest

### ISSUE THREAD

**Issue by r3to** [openTdataCH/ojp-sdk#43]
Example Response: 
https://gist.github.com/r3to/1a253108f7b5a904ce7814626ed078b2

Connection starting 14:19 (12:19Z) is occurring four times in the TripResult. Only observed difference of the trip is the ID 

Environment: Prod
Date: 2024-06-04

**Comment by r3to** [comment]
Another example on `TEST`
Bern - Bern, Bärenplatz

Trip starting at `2024-06-05T13:19:00Z` is occurring four times.

https://gist.github.com/r3to/70a23b04f76d41a6f7ca093fcba62d52/edit

**Comment by TO-mdv** [comment]
Found new example and created a bug: [SH-3238](https://youtrack.mentz.net/issue/SH-3238) OJP2.0 TR doppelte Fahrten in Reponse


![Image](https://github.com/openTdataCH/ojp-sdk/assets/72090402/b0a76f38-8d2b-491a-8042-597bec3ed804)

**Comment by TO-mdv** [comment]
Vermutung Malte. sekundengenaue/Zehntelminuten genaue Echtzeit

**Comment by TO-mdv** [comment]
Doppelte Fahrten sollten nun nicht mehr ausgegeben werden, jedoch kann es sein dass bei NubmerOfResult=4 nun nur noch 1 ausgegeben wird. -> dann neues Bugticket an Malte, min PTKernel Dumps

**Comment by TO-mdv** [comment]
Zwei neue Testfälle erstellt, zusätzlich werden alle TripRequest Testfälle nun auf eindeutige JourneyRef Sequenzen innerhalb Trip in der Response geprüft.

**Comment by TO-mdv** [comment]
Release 12.8.2024 (32-stable)

**Comment by r3to** [comment]
getestet ✅
