### ISSUE TITLE
SKI-1501 Erklärende Echtzeit TripRequest

### ISSUE THREAD

**Issue by TO-mdv** [openTdataCH/ojp-sdk#44]

**Comment by TO-mdv** [comment]
**Testfall 1 - komplett Ausfall einer Fahrt** OK


![Image](https://github.com/user-attachments/assets/9fe7e242-1a0f-4c22-94cb-9a4bf701f452)

**Comment by TO-mdv** [comment]
**Testfall 2 - Anschlusszug fällt aus** OK


![Image](https://github.com/user-attachments/assets/cdc82afe-bc93-4c6b-8975-1ab5e543bfe4)
![Image](https://github.com/user-attachments/assets/58a4ad42-daf1-4ead-be31-2c3cf77b457c)

**Comment by TO-mdv** [comment]
**Testfall 3 - wegen Verspätung Zubringer ist Anschluss nicht gewährleistet** todo: infeasible Flag setzen für Anschlüsse, die evtl. nicht mehr erreicht werden können


![Image](https://github.com/user-attachments/assets/77b3d688-372e-4596-b3bf-9aa5652022ec)
![Image](https://github.com/user-attachments/assets/79529ff2-9d45-4c27-a344-85d3d81416bb)

**Comment by TO-mdv** [comment]
**Vergleich der Ergebnisse, ob mit erklärender Echtzeit, nur Echtzeit oder ohne Echtzeit angefragt wird** OK


![Image](https://github.com/user-attachments/assets/f884ba73-79d0-4bf2-b7e6-5b22b5ec87be)

**Comment by TO-mdv** [comment]
**Testfall 3 - wegen Verspätung Zubringer ist Anschluss nicht gewährleistet** infeasible Flag für Trip, die nicht durchführbar sind, ist nun korrekt umgesetzt. Es wird der ganze Trip markiert, nicht das betroffene Leg. Dies ist im Standard nicht vorgesehen.


![Image](https://github.com/user-attachments/assets/b522392d-15ca-481a-9a2d-ecaafd1203b3)

**Comment by TO-mdv** [comment]
Release 12.8.2024 (32-stable)

**Comment by terencebls** [comment]
done
