### ISSUE TITLE
TR Ausgabe Sitzenbleiber korrigieren

### ISSUE THREAD

**Issue by TO-mdv** [openTdataCH/ojp-sdk#47]
Gemäss OJP weekly von Andreas Glauser:

in OJP1.0 werden Sitzenbleiber als TransferLeg und "remainInVehicle" ausgegeben, das ist auch korrekt so.
in OJP2.0 wird dies als TimedLeg ausgegeben, falsch

**Comment by vasile** [comment]
Similar with https://github.com/openTdataCH/ojp-demo-app-src/issues/125

**Comment by TO-mdv** [comment]
Es geht hier um Sitzenbleiber sowie auch Umstiege, die noch falsch ausgegeben werden.

**Comment by TO-mdv** [comment]
[SH-3137](https://youtrack.mentz.net/issue/SH-3137) OJP2.0 TR Korrektur Ausgabe "Sitzenbleiber"

**Comment by TO-mdv** [comment]
Release on PROD on 27.6.2024
