### ISSUE TITLE
TR with TimedLeg - empty Service.JourneyRef

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#51]
Hi @TO-mdv , please have a look at this TR response
https://gist.github.com/vasile/d96101ace6dea627857a370d0fb1db69

- the first [TimedLeg](https://gist.github.com/vasile/d96101ace6dea627857a370d0fb1db69#file-ojp2_tr_empty_journeyref-xml-L89-L133) `Service` has an empty JourneyRef
```
<JourneyRef />
```

Could it be the case that is a bug for that particular service? The [XSD schema](https://vdvde.github.io/OJP/develop/index.html#DatedJourneyGroup) seems to enforce journey reference.

You can also visualize it here, the first TimedLeg is not drawn at all
https://tools.odpch.ch/ojp-demo-v2/search?gist=d96101ace6dea627857a370d0fb1db69

**Comment by TO-mdv** [comment]
@vasile I cannot reproduce the behaviour. I checked the data in our system, all Journeys have a valid JourneyRef for ICE Basel -  Interlaken Ost. Currently, I'm getting the TimedLeg as expected:


![Image](https://github.com/openTdataCH/ojp-sdk/assets/72090402/a7a9d808-faea-4eef-8d4f-41e7930e1595)


Could it be, that the JourneyRef of missing TimedLeg was overwritten by Realtime Data? Next time you see this behaviour, can you please check on the next day as well if it's missing, there should be no RealtimeData.

**Comment by vasile** [comment]
Hi @TO-mdv - yes, I cant reproduce it either, thats why I've saved the response in the above gist
Before closing the issue can you please first confirm that all `<Service>` should have a JourneyRef present?

**Comment by TO-mdv** [comment]
hi @vasile 
The question is, what should be delivered if there aren't any information to the JourneyRef, no in planned data and neiter in realtime data ?
Currently, like your example, it looks like if we don't get any JourneyRef, we just write <JourneyRef />

What would you expect ?

**Comment by vasile** [comment]
@TO-mdv I am just building the models :) 
Then I'll mark that  expectation that the node is always present but it might be an empty tag, i.e. `<JourneyRef />`

closing the ticket
