### ISSUE TITLE
Routing don't choose the nearby station

### ISSUE THREAD

**Issue by terencebls** [openTdataCH/ojp-sdk#58]
If you make a Trip Request with the Adress Sägemattstrasse 1, Köniz as departure point, we get  as checkin station Liebefeld hesstrasse, instead of Köniz Brühlplatz.

https://tools.odpch.ch/ojp-demo-v2/search?from=46.926930,7.416140(Sägemattstrasse%201%20(Köniz))&to=8505000&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-07-09%2009:58&stage=v2-prod

**Comment by Flurin-BLS** [comment]
Habe dieses Ticket als Bug und Blocker gelabeled. Ist eine Funktion die auf V1 einwandfrei funktioniert, in 2.0 leider aber nicht. Gute einfacher Request um zu testen ist die Sägemattstrasse 1 - unser Bürostandort in Köniz.

**Comment by TO-mdv** [comment]
The problem is, that currently the footway to the first stop is not taking into account for tripcalculation. Will be fixed by [#24](https://github.com/openTdataCH/ojp-sdk/issues/24)

**Comment by TO-mdv** [comment]
Test on the TEST System successful:


![Image](https://github.com/user-attachments/assets/8df77cf4-541d-4e1f-839a-7b99b7e1ec69)

**Comment by TO-mdv** [comment]
Release 12.8.2024 (31-stable)
