### ISSUE TITLE
TR Via und Dwell Time - Aufenthaltszeit

### ISSUE THREAD

**Issue by TO-mdv** [openTdataCH/ojp-sdk#59]

**Comment by u233336** [comment]
Für QuoVadis ist die ein "wichtiges" Feature. Eine Umstellung auf OJP 2.0 wird bei ihnen erst dann in Betracht gezogen, wenn dieses Feature da ist. Daher für unser PI 20 einplanen

**Comment by TO-mdv** [comment]
Aufgrund der Prioriserung von Support Language und Blocker Bugs wird dieses Feature wohl nicht im laufenden Sprint umgesetzt.
@u233336 das müssen wir neu priorisieren bitte

**Comment by u233336** [comment]
@TO-mdv für mich völlig OK. Wir müssen schauen, ob wir das in der 2. Hälfte September noch einplanen können und welchen Impact das auf QuoVadis haben wird. Joel Jufer wartet auf dieses Feature.
