### ISSUE TITLE
GoldenPass trains don't appear in Trips

### ISSUE THREAD

**Issue by terencebls** [openTdataCH/ojp-sdk#62]
The golden pass trains don't Appear in the Trip response.

Example: direct connections for Montreux - Interlaken West: http://haf.as/68Yc

**Comment by r3to** [comment]
Wird erst im Rahmen von [#52](https://github.com/openTdataCH/ojp-sdk/issues/52) umgesetzt –> also nicht bereit für den geplanten Release

**Comment by TO-mdv** [comment]
Ticket intern erstellt, möglicherweise Einfluss durch Flügelung: [EFABA-4359](https://youtrack.mentz.net/issue/EFABA-4359) Direkte Verbindung Montreux-Interlaken West (GPX PE Panoramaexpress) fehlt
