### ISSUE TITLE
TR start/end ContinousLeg with broken Duration 

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#63]
Given any TR with coords/coords to coords/coords
https://tools.odpch.ch/ojp-demo-v2/search?from=46.934470,7.442040&to=46.931814,7.438296&stage=v2-int&do_search=yes

first / last legs are `ContinousLeg` type and have invalid Duration
<img width="1358" alt="image" src="https://github.com/user-attachments/assets/933ca2bf-f261-4bf6-9ce4-b00a860aae1e">

In addition, no information is returned about the distance
check OJP v1 for comparison
https://tools.odpch.ch/beta-ojp-demo/search?from=46.934470,7.442040&to=46.931814,7.438296&do_search=yes

**Comment by Flurin-BLS** [comment]
Is this Bug still correct? Or is it fixed by https://github.com/openTdataCH/ojp-sdk/issues/24 or
https://github.com/openTdataCH/ojp-sdk/issues/58 
@vasile ? @herlitze ?

**Comment by vasile** [comment]
@Flurin-BLS  It looks like it's fixed, closing it now
