### ISSUE TITLE
LIR: Requests for stops with special characters don't work

### ISSUE THREAD

**Issue by bls-marco** [openTdataCH/ojp-sdk#64]
LIR isn't showig result which contain special characters ("/"), like these examples: 

- Murten/Morat
- Biel/Bienne
- Domat/Ems

If request contains Murten, Biel and Domat, the response isn't containing the expected stop. 

Requests with the name after the slash work fine. Request for Morat, Bienne and Ems show expected results.

![16-07-2024_11-42-59](https://github.com/user-attachments/assets/5297c778-17ed-4210-89a1-2eba9b49e480)

**Comment by TO-mdv** [comment]
Fixed on INT


![Image](https://github.com/user-attachments/assets/184af646-a44b-4db7-8647-20d040993b4d)



![Image](https://github.com/user-attachments/assets/446579d6-a1c3-44af-b23a-33269bc6d5c9)



![Image](https://github.com/user-attachments/assets/e315f6f4-8392-4d63-97be-84006acb112a)



![Image](https://github.com/user-attachments/assets/079108dd-9cab-44f9-a911-dbcc7333c23e)



![Image](https://github.com/user-attachments/assets/0aaef6d8-bfd2-480a-bea8-0b0073912859)

**Comment by TO-mdv** [comment]
Configuration Released 26.8.2024

**Comment by terencebls** [comment]
fixed
