### ISSUE TITLE
TR: Train don't appear in some requests

### ISSUE THREAD

**Issue by terencebls** [openTdataCH/ojp-sdk#65]
Given this request (Trip Bern - Lugano), we get 10 connections.

`<OJP xmlns="http://www.vdv.de/ojp" xmlns:siri="http://www.siri.org.uk/siri" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0"> 
	<OJPRequest> 
		<siri:ServiceRequest> 
			<siri:RequestTimestamp>2024-07-17T06:46:08Z</siri:RequestTimestamp> 
			<siri:RequestorRef>BLS_IOS_SDK_0.1.0</siri:RequestorRef> 
			<OJPTripRequest> 
				<siri:RequestTimestamp>2024-07-17T06:46:08Z</siri:RequestTimestamp> 
				<Origin> 
					<PlaceRef> 
						<StopPlaceRef>8507000</StopPlaceRef> 
						<Name> 
							<Text>Bern</Text> 
						</Name> 
					</PlaceRef> 
					<DepArrTime>2024-07-17T14:00:00Z</DepArrTime> 
				</Origin> 
				<Destination> 
					<PlaceRef> 
						<StopPlaceRef>8505300</StopPlaceRef> 
						<Name> 
							<Text>Lugano</Text> 
						</Name> 
					</PlaceRef> 
				</Destination> 
				<Params> 
					<NumberOfResults>10</NumberOfResults> 
					<IncludeLegProjection>false</IncludeLegProjection> 
					<IncludeIntermediateStops>true</IncludeIntermediateStops> 
					<IncludeAllRestrictedLines>true</IncludeAllRestrictedLines> 
				</Params> 
			</OJPTripRequest> 
		</siri:ServiceRequest> 
	</OJPRequest> 
</OJP>`

The result is a list of trains, where at the end of the list there are one train starting at 20:02 and then one starting at 21:02:

<img width="316" alt="image" src="https://github.com/user-attachments/assets/2d927922-0894-4341-bab1-6001a2548d1f">

But if we make the same request, 30 Minutes later:

`<OJP xmlns="http://www.vdv.de/ojp" xmlns:siri="http://www.siri.org.uk/siri" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0"> 
	<OJPRequest> 
		<siri:ServiceRequest> 
			<siri:RequestTimestamp>2024-07-17T06:53:37Z</siri:RequestTimestamp> 
			<siri:RequestorRef>BLS_IOS_SDK_0.1.0</siri:RequestorRef> 
			<OJPTripRequest> 
				<siri:RequestTimestamp>2024-07-17T06:53:37Z</siri:RequestTimestamp> 
				<Origin> 
					<PlaceRef> 
						<StopPlaceRef>8507000</StopPlaceRef> 
						<Name> 
							<Text>Bern</Text> 
						</Name> 
					</PlaceRef> 
					<DepArrTime>2024-07-17T14:30:00Z</DepArrTime> 
				</Origin> 
				<Destination> 
					<PlaceRef> 
						<StopPlaceRef>8505300</StopPlaceRef> 
						<Name> 
							<Text>Lugano</Text> 
						</Name> 
					</PlaceRef> 
				</Destination> 
				<Params> 
					<NumberOfResults>10</NumberOfResults> 
					<IncludeLegProjection>false</IncludeLegProjection> 
					<IncludeIntermediateStops>true</IncludeIntermediateStops> 
					<IncludeAllRestrictedLines>true</IncludeAllRestrictedLines> 
				</Params> 
			</OJPTripRequest> 
		</siri:ServiceRequest> 
	</OJPRequest> 
</OJP>`

We get a train that is also starting at 21:00, which was not present in the previous response:

<img width="399" alt="image" src="https://github.com/user-attachments/assets/cf0cada4-5ebb-4a92-8faa-52312fee799a">

**Comment by herlitze** [comment]
@terencebls the IR15 is an alternative connection to IC81 since they arrive in Lugano at the same time. Alternatives are found in one run, for the first request we have found 9 results and start another run to get the 10th requested result. We now find find both IR15 and IC81. Since 10 Results are requested we throw away one of them. With a later requested departure, we can keep both results.
We could stop removing results and just return more than the requested number of results.

**Comment by TO-mdv** [comment]
@terencebls  is this issue resolved? Then please set it to DONE

**Comment by terencebls** [comment]
I think that we should find a solution for that. Because if the user scroll down the connections, and the application load new connections (in the future), it's not correct that a connection suddenly appears that was not in the list before.

**Comment by herlitze** [comment]
@terencebls does my suggested solution to stop removing results and return more than the requested number of results work for you?

**Comment by terencebls** [comment]
Yes 👍

**Comment by TO-mdv** [comment]
Bug intern: [SH-3420](https://youtrack.mentz.net/issue/SH-3420) TR: Train don't appear in some requests

**Comment by TO-mdv** [comment]
Release on PROD 22.8.2024
