### ISSUE TITLE
TR: StartTime has strange seconds component

### ISSUE THREAD

**Issue by terencebls** [openTdataCH/ojp-sdk#66]
In some connections the startTime has some strange data:

![image](https://github.com/user-attachments/assets/f3ccbb42-b8ed-48d1-96ab-68d26cb0624c)

In this case the train starts at 08:55:18. 

In my opinion the seconds should be 0 instead of 18.

**Comment by TO-mdv** [comment]
Die Sekunden kommen von der Echtzeit, diese wird seit Anfang 2024 zehntelminuten-genau geliefert.
Die StartTime entspricht immer der EstimatedTime des LegBoard
Die EndTime entspricht immer der EstimatedTime des LegAligth

Eine Anfrage in der Zukunft wird keine sekundengenaue Zeiten liefern.

**Comment by TO-mdv** [comment]
dies kann dann dazu führen, dass eine wenige Sekunden zu frühe Ankunft zu einem -1min führt, was jedoch aus OJP API Sicht korrekt ist. Diese Darstellung müsste im Client gelöst werden:
![image](https://github.com/user-attachments/assets/844fcd35-e7f0-4357-95e9-18aab0eb104c)

```
<Trip>
    <Id>ID-87ABA3B8-0203-4AA5-A90D-BC544DAB7286</Id>
    <Duration>PT13M12S</Duration>
    <StartTime>2024-07-22T12:02:30Z</StartTime>
    <EndTime>2024-07-22T12:15:42Z</EndTime>
    <Transfers>0</Transfers>
    <Leg>
        <Id>1</Id>
        <Duration>PT13M12S</Duration>
        <TimedLeg>
            <LegBoard>
                <siri:StopPointRef>ch:1:sloid:5300:2:3</siri:StopPointRef>
                <StopPointName>
                    <Text xml:lang="de">Lugano</Text>
                </StopPointName>
                <PlannedQuay>
                    <Text xml:lang="de">3</Text>
                </PlannedQuay>
                <EstimatedQuay>
                    <Text xml:lang="de">3</Text>
                </EstimatedQuay>
                <NameSuffix>
                    <Text xml:lang="de">NO_DATA</Text>
                </NameSuffix>
                <ServiceDeparture>
                    <TimetabledTime>2024-07-22T12:02:00Z</TimetabledTime>
                    <EstimatedTime>2024-07-22T12:02:30Z</EstimatedTime>
                </ServiceDeparture>
                <Order>1</Order>
            </LegBoard>
            <LegAlight>
                <siri:StopPointRef>ch:1:sloid:5213:1:1</siri:StopPointRef>
                <StopPointName>
                    <Text xml:lang="de">Bellinzona</Text>
                </StopPointName>
                <NameSuffix>
                    <Text xml:lang="de">NO_DATA</Text>
                </NameSuffix>
                <PlannedQuay>
                    <Text xml:lang="de">1</Text>
                </PlannedQuay>
                <EstimatedQuay>
                    <Text xml:lang="de">1</Text>
                </EstimatedQuay>
                <ServiceArrival>
                    <TimetabledTime>2024-07-22T12:16:00Z</TimetabledTime>
                    <EstimatedTime>2024-07-22T12:15:42Z</EstimatedTime>
                </ServiceArrival>
                <Order>2</Order>
            </LegAlight>
```

**Comment by Flurin-BLS** [comment]
Hier kommt der Zug um 13:16 in Bellinzona, aber OJP gibt zurück als endTime 13:15:42, so wird dann mit 13:15 dargestellt. 
![image](https://github.com/user-attachments/assets/3ffe059b-9c4d-4aaf-8833-da89c2b77990)

**Comment by Flurin-BLS** [comment]
News: Laut Andreas Glauser und Thomas Odermatt ist das so gewollt, dass wir erhalten bei eine Verbindung die genaue startZeit und endZeit in Sekunden genaue. Die Problematik hier ist dass wir wissen nicht, auf der Trip ebene, ob der Trip hat eine Verspätung. Erst auf der Legs ebene wissen wir ob eine Leg hat eine Verspätung. D.h. wir müssen entweder ein workaround einbauen um die heutige Darstellung zu repräsentieren (mit der +3), oder etwas ändern an die Darstellung.

**Comment by terencebls** [comment]
ok
