### ISSUE TITLE
OJP2.0 SER liefert keine Attribute

### ISSUE THREAD

**Issue by TO-mdv** [openTdataCH/ojp-sdk#68]
[SH-3328](https://youtrack.mentz.net/issue/SH-3328) OJP2.0 SER liefert keine Attribute

**Comment by TO-mdv** [comment]
Release 12.8.2024 (30-stable)

**Comment by vasile** [comment]
@TO-mdv, @herlitze  this can be closed, right?

**Comment by r3to** [comment]
close, as it is archived in the project
