### ISSUE TITLE
TR: weird results around midnight

### ISSUE THREAD

**Issue by r3to** [openTdataCH/ojp-sdk#72]
For TripRequests around midnight, we get a strange response:

<img width="1243" alt="image" src="https://github.com/user-attachments/assets/ac315557-df8e-44b7-bb6a-51334db3c61c">

The highlighted trip's Start/EndTime is according to the XML Response:

``` xml
<StartTime>2024-07-30T22:16:00Z</StartTime>
<EndTime>2024-07-31T03:52:00Z</EndTime>
```

or `2024-07-31T00:16:00+02:00` - `2024-08-01T05:52:00+02:00` (MESZ)

This would be **1 day** before the other results.

Maybe this is related to #71 

Educated guess: the UTC timezone is not taken into account, when filtering trips.

[Request on Gist](https://gist.github.com/r3to/7396865b219d80aa90b830ec76833249)

**Comment by TO-mdv** [comment]
UTC timezone is now taking into account, date/time is now correct, also sorting:


![Image](https://github.com/user-attachments/assets/4b8637ed-a4db-48e4-a0b2-8273f1a6942d)

**Comment by TO-mdv** [comment]
Release 12.8.2024 (32-stable)

**Comment by r3to** [comment]
Gefixt, Danke @TO-mdv! 👍
