### ISSUE TITLE
OJP 2.0 API and SDK Testing

### ISSUE THREAD

**Issue by Flurin-BLS** [openTdataCH/ojp-sdk#76]
Es kommt häufig vor das etwas als "umgestzt" von Mentz released wird und wir dann aber feststellen das es einige Fälle gibt die noch nicht funktionieren.
Wie können wir in Zukunft sicherstellen das mehr Fälle möglichst automatisiert getestet werden?

- Was wird von OJP (SKI+) oder Mentz getestet bevor etwas "released" wird? --> Testabdeckung
- Was und wie wird heute mit HAFAS getestet?

**Comment by Flurin-BLS** [comment]
Was wird heute wie getestet?
- Zur Zeit wird nur manuell getestet - es gab mal automatische Tests, sind aber nicht mehr aktiv
**- Wer testet was? Testszenarien durchspielen**
Fragen:
- Wie wird die Datenqualität von TUs überprüft?
- --> OJP bezieht Daten aus INFO+ --> wenn da etwas fehlt, fehlt es bei SBB als auch im OJP
- --> Datenqualtitä muss weiter vorne in der Kette "gesichert" werden --> für Behig gibt es ein Dashboard

**Comment by Flurin-BLS** [comment]
Fotokoll aus dem Boost Camp:

![Image](https://github.com/user-attachments/assets/ed0a42b4-b22b-423c-b8e9-aa15d82fc041)

![Image](https://github.com/user-attachments/assets/a1b463d4-cd34-416e-bc78-b21257825875)

**--> Dani setzt einen Follow-Up Termin auf.**

**Comment by TO-mdv** [comment]
**XSD Validierung**
Hier gab es bereits in OJP1.0 Versuche, das Schema bei jedem Request/Response zu validieren. Dies wurde aufgrund von Performanceeinbusen wieder eingestellt. Daher auch bei OJP2.0 nicht vorgesehen.
Matthias Günter hat jedoch alle Responses in der Testcollection validiert und ein issue zur Behebung erstellt. Darum kümmern wir uns. #89

**Comment by schmutzdan2** [comment]
Austausch von SKI+, Mentz und BLS vom Freitag, 23.08.2024 15:00 - 16:00
- Anwesend: SKI+ Andreas Glauser, Mentz: Thomas Odermatt, BLS: Daniel Schmutz

Ergebnisse:
- SKI+ ist keine Datenpolizei, BLS "darf" selbstständig auf die Datenlieferanten zugehen, wenn diese die Daten nicht einliefern
- SKI+: Grösster Teil der Probleme kann bei der Datenlieferung ausgemacht werden - Keine Testcases
- sKI+: Bei Algorithmus Fehlern werden die Testcases aufgenommen
- Einlieferungsformat der Findings von BLS SoapUI collection / Postman (Alternativ aus OJP-Demo App Permalink kopieren)
- BLS schaut, ob die automatischen Tests zeitlich vorgezogen werden können. INT 19:00 - 21:00 wäre ideal , Test bis 20:00
- Andreas ist ab 13. September wieder verfügbar
- Freitag wird weiterhin als idealer Tag für die Terminserie betrachtet

Link auf Concept-Board: https://app.conceptboard.com/board/cg5k-q8y9-dxbh-9arr-s13t

**Comment by Flurin-BLS** [comment]
Gemäss Diskussion von heute sind die Punkte für @TO-mdv und @u233336 geklärt. Ich kläre die Punkte noch BLS-Intern, danach Ticket schliessen.

**Comment by Flurin-BLS** [comment]
Unit Tests Automatisiert bei MENTZ Entwicklung bei jedem Build
Funktionstest Neue Funktionen bei nicht freigegebenen Versionen testen, durch Supportteam MENTZ SBB.
Integrationstest Im MENTZ Testing Team angesiedelt, bei jeder Programmfreigabe. Automatisierte Test's mit Timemachine und manuell eingespielter Echtzeitmeldungen.
End-to-end Test Bei Supportteam MENTZ SBB SBB angesiedelt. Bei jedem Daten-, Programm- oder Konfigurationsupdate angewendet. (Postman Collection)
Performance Test durch SKI+/SBB. Ein Cronjob sendet täglich ein definiertes Set von Requests und misst die Responsezeiten.

**Comment by Flurin-BLS** [comment]
Nach Rücksprache mit Dani ist folgender Punkt noch offen:
- Für SDK-Tesging - SoapUI-Test von Mentz mit SBB ausgetauscht? - ist das nun passiert oder wie ist der Stand?

Prozess für Findings auf Seite BLS:
- Dani erstellt eine "Landingpage" bei BLS wo Fehler gesammelt werden - Unterseite von https://confluence.bls.ch/x/MQ3lBg
- BLS macht Triage
- Fehler werden je nach Thema in einem der bestehenden Meetings eingebracht (DEV, Bi-Weekly oder Betriebsmeeting)
