### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by Flurin-BLS** [openTdataCH/ojp-sdk#77]
Das heutige Monitoring ist für die Messung vom SLA als auch für uns zur Qualitätssicherung unzureichend.

Damit wir BLS Mobil mit OJP 2.0 mit gutem gewissen Produktiv schlaten können. Müssen die SLA's messbar sein.

Zur Zeit ist es nicht möglich die Ausfälle oder die Up-Time über einen gewünschten Zeitraum pro API zu visualisieren.

- Auf dem Statuscake von [Opentransportdata](https://status.opentransportdata.swiss/) ist nur OJP2.0 over all zu sehen und max. 1 Monat
- Auf dem [Statuscake von Mentz](https://app.statuscake.com/Bigscreen/display.php?id=4e982c1f-2f37-4aa6-8035-88a09ac631a8)e weiss man weder welcher Zeitraum noch kann sonst etwas angepasst werden

**Comment by Flurin-BLS** [comment]
Erwartungen BLS:
**- Mehr Zugriff/Berechtigung auf Statuscake mit mehr Details?**
- SLA? 5 Ausfälle pro Jahr --> wie wird das gemessen? --> SKI+ liefert Quartals-Reporting an BAV --> kann auch als Kopie an BLS gesendet werden --> Tobi liefert entsprechende Mailadresse
- SMS-Alert hat Tobi schon abonniert
- ZEBIX --> macht eine regelmässige Abfrage auf den TR
- Bitrise --> @terencebls hat auch eine Abfrage auf den TR eingerichtet --> herunterfahren wenn Zabbix ready ist
**- DryRun bei Incident durchführen**

**Comment by Flurin-BLS** [comment]
Tobi braucht noch einen GitHub User --> sobald dem BLS-Team zugeordnet kann dieses Ticket auch ihm assigned werden

**Comment by Flurin-BLS** [comment]
Open points:

- Monitoring wird intern aufgebaut mittels Zabbix​ > @tobiaszurbriggen 
 -- Bei Störung wird Sikado – Alarm ausgelöst (SMS, Telefon, E-Mail)​

- Externes Monitoring wird noch angepasst​
-- Zugriffe auf Statuscake wird geprüft seitens SKI+​ > @AndreasAtSBB 

- SLA: Monatliches Reporting analog BAV wird auch an BLS geliefert​ > @u233336 

- DryRun für ein Incident durchführen > @tobiaszurbriggen

**Comment by TO-mdv** [comment]
Dashboard: https://uptime.statuscake.com/?TestID=nPKk9Dbgid
https://app.statuscake.com/Bigscreen/display.php?id=4e982c1f-2f37-4aa6-8035-88a09ac631a8

**Comment by Flurin-BLS** [comment]
Hey @tobiaszurbriggen - konntet ihr dem DryRun schon aufgleisen? Und wie ich gehört habe, bist du ja mit Zabbix dran, oder? Gerne kurzes Update hier im Ticket. Merci

**Comment by tobiaszurbriggen** [comment]
Hey @Flurin-BLS - Betreffend DryRun: noch nicht, aber ich habe gerade mit Marco darüber gesprochen, dass wir nun unbedingt einen Termin aufsetzen müssen. Und zum Thema Monitoring: Richtig, ich bin aktuell dran ein Monitoring auf unserer Seite mit Hilfe von Zabbix aufzugleisen. Wie wie Abfragen ist noch nicht ganz klar, es kann über den API GW oder direkt die OJP API sein. 

Sobald ich mehr Infos habe, kann ich euch gerne Informieren.

**Comment by Flurin-BLS** [comment]
The Monitor shows 12 days "UP-time" - but the service was down... usualy the "down-time" during the night is shown with a peak, but there is no peak during the last 12 days...
Seems a bit tricky to read this monitor.. we need further explenation.
TEST-TR - no picks
![Image](https://github.com/user-attachments/assets/a5fab132-32f8-4ab4-890b-fa774a72c5ba)

INT-TR - a peak every night when the system is not available
![Image](https://github.com/user-attachments/assets/61c8a12e-f545-4698-a9b7-de85f3d04b91)

**Comment by Flurin-BLS** [comment]
I've assigned @AndreasAtSBB to the ticket, please clarify the monitoring "rules" - thanks

**Comment by AndreasAtSBB** [comment]
Also nun werden nur noch INT und PROD im Monitoring angezeigt https://uptime.statuscake.com/?TestID=nPKk9Dbgid:
TEST wurde gar nicht gepollt, deshalb die etwas verwirrende Anzeige.
Der aktuelle Status ist jeweils hier so sichtbar: 
![image](https://github.com/user-attachments/assets/73f4a02d-5d30-4227-a397-9c5a3587572b)

Die Anzeige in Statuscake entspricht der SLA, wenn diese nicht erreicht wird verfärbt sich der Bullet von diesem Tag und bleibt auch in dieser Farbe. Da INT aktuell in der Nacht abgestellt wird, wird es auch rot angezeigt.
Bei Mentz läuft noch ein zusätzliches Monitoring und auch eine statistische Überwachung mit OpenSearch.
Die Incidents werden in den Quartalsreports ausgewiesen, dort werden auch die Gründe angegeben, warum es zum Ausfall kam.
Das Public-Monitoring ist hier: https://status.opentransportdata.swiss/

Dies zum Monitoring der SBB.
Wir empfehlen der BLS ebenfalls ein unabhängiges Monitoring mit Logs einzurichten. Dies könnte allenfalls im Incident-Fall helfen Ursachen aufzuklären.
