### ISSUE TITLE
Roadmap und Zusammenarbeit SKI+ - Mentz - BLS

### ISSUE THREAD

**Issue by Flurin-BLS** [openTdataCH/ojp-sdk#79]
Wie soll die Zusammenarbeit in Zukunft aussehen?

Heute gibt es folgende Termine, Prozesse und Kommunikationskanäle:
- Weekly OJP 2.0 Mobile SDK Sync - Lead?
- SKI+ & BLS: Meeting zum OJP - Lead Jan Eijsten
- Sprints BLS-Mobil Team
- Sprints Mentz-SKI+
- Sprints SKI+?
- Slack-Channels für DEVs SKI+ und BLS --> besser wäre eine Kanal wo alle zugriff haben, auch Mentz
- Welche Boards zu welchem Zweck? --> was ist Public was besser nicht?

**Comment by Flurin-BLS** [comment]
Hier bitte nichts kommentieren... ist nur als Platzhalter fürs Boost Camp gedacht

**Comment by Flurin-BLS** [comment]
Alle offenen Action Items sind in Confluence erfasst: https://confluence.sbb.ch/x/zbc_qQ

Die Doku der wichtigsten "Zusammenarbeits-Themen" sind im Wiki hier auf Git Hub festgehalten worden von mir und @r3to https://github.com/openTdataCH/ojp-sdk/wiki/Meeting-and-process-for-OJP-SDK-development

Schliesse daher dieses Ticket - FYI @TO-mdv , @vasile, @AndreasAtSBB , @u233336

**Comment by Flurin-BLS** [comment]
Zum unsere "labels" zu testen noch "decision-needed" gesetzt, so können wir es im nächsten Bi-Weekls gemeinsam schliessen.

**Comment by vasile** [comment]
@Flurin-BLS this is now in `Done`, can be closed?

**Comment by Flurin-BLS** [comment]
Hi @vasile , I want to demonstrate the use of the labels for the BI-Weekly with this ticket.. that's why I haven't made the status change... will do in the next Bi-Weekly call, ok?
