### ISSUE TITLE
TR: Situations with same `SummaryText` appears 7 times on the same leg

### ISSUE THREAD

**Issue by r3to** [openTdataCH/ojp-sdk#83]
```xml
<siri:PublishingActions>
                <siri:PublishingAction>
                  <siri:PassengerInformationAction>
                    <siri:RecordedAtTime>0001-01-01T00:00:00</siri:RecordedAtTime>
                    <siri:TextualContent>
                      <siri:SummaryContent>
                        <siri:SummaryText xml:lang="de">Der Bahnverkehr auf der Strecke Palézieux - Allaman ist zwischen Lausanne und Allaman eingeschränkt.</siri:SummaryText>
                      </siri:SummaryContent>
```

this is appearing seven times on the Leg `Fribourg-Lausanne`. 

[Gist](https://gist.github.com/r3to/1458b66fc0b434850052f61a302f33b2)

<img width="380" alt="image" src="https://github.com/user-attachments/assets/19f0bb0e-24ab-4572-babb-d2bb61c0fac6">

**Comment by TO-mdv** [comment]
Die Meldung wurde wohl vom TU mehrfach erfasst. @u233336 kannst du das bitte mal mit Roger klären?
`Der Bahnverkehr auf der Strecke Palézieux - Allaman ist zwischen Lausanne und Allaman eingeschränkt.`


![Image](https://github.com/user-attachments/assets/a8851e23-c40a-406d-8dae-c452a526b568)

**Comment by u233336** [comment]
Ich hab's mit Roger Kneubühl angeschaut. Hier seine Antwort:

_Hallo Christoph

Ich gehe davon aus, dass du die vielen «Die Einschränkung dauert ….» meinst? Oder geht es um das schlecht gewählt PublicationWindow für die Perspektive stopPoint?

Beides ist bekannt und bei VIA deponiert.

Beim OJP dürften die Ereignisse nur beim StopEventRequest angezeigt werden. Kannst du mir noch einen Request liefern, wo BLS beim OJP diese Ereignisse gefunden hat?_

Zudem: derzeit sehe ich die Störungen zwischen Lausanne und Allaman im OJP nicht mehr, eigentlich sehe ich derzeit keine Störungen im OJP

**Comment by r3to** [comment]
@u233336 die Ereignisse kamen beim TripRequest in [diesem Beispiel](https://gist.github.com/r3to/1458b66fc0b434850052f61a302f33b2)

**Comment by u233336** [comment]
Wir werden das mit den VErantwortlichen EMS klären

**Comment by r3to** [comment]
@u233336 hast du ein Update, resp. können wir dieses Issue schliessen?

**Comment by u233336** [comment]
Ich würde dieses Issue schliessen, denn die Störungsmeldungen wurden so "falsch" / "schlecht" angezeigt, weil sie so schlecht oder gar falsch erfasst wurden. Der Ball liegt nun bei der Schulung der EMS Usern

**Comment by r3to** [comment]
👍

**Comment by u233336** [comment]
Und es ist ein Bug in EMS und wird im nächsten PI gefixed
