### ISSUE TITLE
TR: If a trip is cancelled EstimatedTime returns 0001-01-01T00:00:0

### ISSUE THREAD

**Issue by deka91** [openTdataCH/ojp-sdk#85]
**Description**
I tested following trip with "Unterbruch": _Meiringen - Interlaken Ost_
For the cancelled trip we always receive _0001-01-01T00:00:00_ for _EstimatedTime_ which is not a valid datetime

**Expected Behavior**
We shouldnt receive any EstimatedTime when the trip is cancelled.

**Current Behavior**
We receive _0001-01-01T00:00:00_ for _EstimatedTime_ when the trip is cancelled.

**Steps to Reproduce**
Make a TripRequest for a cancelled trip because of disturbance.
E.g.: Meiringen - Interlaken Ost
Look up for trips with a disturbance on the disturbances overview.

**Ressources**
- TripResponse: https://gist.github.com/deka91/eee03c65f700d12e1faf7f2a82c319f2
- Overview of disturbances: https://www.sbb.ch/de/reiseinformationen/bahnverkehrsinfo/betriebslage-stoerungen.html?bbox=eyJ0b3AiOlszLjg3MDgyNTgyNjQ4NzA0OTQsNDQuODY0MTQxMTMzNTY5MjldLCJib3R0b20iOlsxMi41MzE3NzQxNzM1MDc2MTQsNDguNjgzMjMxMzkzMTExMTZdfQ%253D%253D

**Comment by TO-mdv** [comment]
Bug erstellt: [SH-3465](https://youtrack.mentz.net/issue/SH-3465) OJP2.0 TR EstimatedTime = 0001-01-01T00:00:00

**Comment by TO-mdv** [comment]
Fixed and tested. All Testcases extended to check for this "invalid" date/time object

**Comment by TO-mdv** [comment]
Release on PROD 22.8.2024 (41-stable)
