### ISSUE TITLE
LIR "Ba" + No Type Restriction return stops with wrong coordinates

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#9]
https://tools.odpch.ch/ojp-api-explorer-v2/?gist=ccdb179fce144d17ff7329ce5bbcb8f8

<img height="400" alt="image" src="https://github.com/openTdataCH/ojp-sdk/assets/113994/a4ce5020-37a7-4ecc-8e3a-5b9cd6f05a0c">

- problem 1 - there are `TopographicPlace ` results without coordinates (no GeoPosition)
```
<TopographicPlace>
  <TopographicPlaceCode>24074208:3</TopographicPlaceCode>
  <TopographicPlaceName>
    <Text xml:lang="de">Bay (H-Savoie)</Text>
  </TopographicPlaceName>
</TopographicPlace>
```
- problem 2 - some entries have mixed up coordinates (long / lat), they are rendered in Africa
```
<Place>
  <TopographicPlace>
    <TopographicPlaceCode>9187128:7</TopographicPlaceCode>
    <TopographicPlaceName>
      <Text xml:lang="de">Bach (Bad Endorf)</Text>
    </TopographicPlaceName>
  </TopographicPlace>
  <Name>
    <Text xml:lang="de">Bach (Bad Endorf)</Text>
  </Name>
  <GeoPosition>
    <siri:Longitude>47.86667</siri:Longitude>
    <siri:Latitude>12.3</siri:Latitude>
  </GeoPosition>
</Place>
```

Request
`/POST https://api.opentransportdata.swiss/ojp20`
XML: https://gist.github.com/vasile/ccdb179fce144d17ff7329ce5bbcb8f8

**Comment by vasile** [comment]
@u233336 please have a look at the coords outside of EU

**Comment by u233336** [comment]
Ticket about to be analyzed! We believe it is an error in the MENTZ DB for topographicPlaces, since the coordinates are OK in atlas, INFO+ and the HRDF-Export.

**Comment by TO-mdv** [comment]
Probelm resolved, in certain LocationPlaces were reversed Lat/Lon coordianates

![Image](https://github.com/openTdataCH/ojp-sdk/assets/72090402/c915f8c6-9776-411e-ad14-40d05b3d3279)

**Comment by TO-mdv** [comment]
Release on INT and PROD on 6.6.2024 (it's not a bugfix, it's a change in the configuration of the data processing)
