### ISSUE TITLE
TR Autoverlad - Empty TripId

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#92]
Expected a value for `TripResult/Id` and `TripResult/Trip/Id` nodes, got empty nodes instead:

```
<TripResult>
    <Id />
    <Trip>
        <Id />
        <Duration>PT39M59S</Duration>
        <StartTime>2024-08-15T22:12:00Z</StartTime>
        <EndTime>2024-08-15T22:51:59Z</EndTime>
        <Transfers>2</Transfers>
        <Distance>33990</Distance>
```

Request / response (PROD, but is broken also on TEST)
https://gist.github.com/vasile/97f6c21222a332903863ecfbbdf6682d

Test URL: https://tools.odpch.ch/ojp-demo-v2/search?from=8576367&to=46.320059,7.754451&mode_types=monomodal&transport_modes=self-drive-car

**Comment by TO-mdv** [comment]
Already fixed on PROD
