### ISSUE TITLE
TR - Ersatzverkehr services with UseRealtimeData=explanatory returns 5xx error

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-sdk#93]
TR requests with `<UseRealtimeData>explanatory</UseRealtimeData>` return 5xx errors

```
<Params>
  <NumberOfResults>5</NumberOfResults>
  <IncludeTrackSections>true</IncludeTrackSections>
  <IncludeLegProjection>true</IncludeLegProjection>
  <IncludeTurnDescription>true</IncludeTurnDescription>
  <IncludeIntermediateStops>true</IncludeIntermediateStops>
  <UseRealtimeData>explanatory</UseRealtimeData>
</Params>
```

=> 

```
{
    "traceId": "7a2f8662-5cce-4514-b5af-d3fb4276f33b",
    "error": "Sequence contains no elements",
    "host": "6d82b534d0ae"
}
```

<img width="980" alt="image" src="https://github.com/user-attachments/assets/3228ddcc-497b-4d82-be80-5c456a8ebdf4">

TR GIST: https://gist.github.com/vasile/0462c5948119ad859f644d7fecfd2a37

**Comment by TO-mdv** [comment]
created a bug: [SH-3456](https://youtrack.mentz.net/issue/SH-3456) OJP2.0 TR mit Erklärender Echtzeit liefert 500-Sequence contains no elements

**Comment by TO-mdv** [comment]
Release on PROD 22.8.2024 (40-stable)

**Comment by vasile** [comment]
Looks good to me, closing
