### ISSUE TITLE
SDK: Handling of empty lists

### ISSUE THREAD

**Issue by r3to** [openTdataCH/ojp-sdk#94]
<img width="657" alt="image" src="https://github.com/user-attachments/assets/7ce98b62-66df-47b3-9704-f8f802ddd825">

Elements that have cardinality `0:*` can both be represented as `Nullable-Lists` or `Lists that could be empty`.

→ Define a common approach here

**var a) `Nullable Lists`**

- have to be unwrapped and checked for `!isEmpty` in order to find out, if there is something inside

**var b) `Empty Lists`**

- don't have to be unwrapped
- check for `!isEmpty` to find out if there is something in it

**Comment by vasile** [comment]
I am in favor of b) for simplicity but also for data model readability

**Comment by r3to** [comment]
same here

**Comment by terencebls** [comment]
I'm also for b :)

**Comment by r3to** [comment]
Closing with decision for **b)**
