### ISSUE TITLE
Two foot paths instead of one

### ISSUE THREAD

**Issue by terencebls** [openTdataCH/ojp-sdk#96]
Two Footway are returned.

If we make a Trip search for Bern, Humboldtstrasse 41 - Basel we get two Footpaths at the beginning instead of one:

<img width="391" alt="image" src="https://github.com/user-attachments/assets/21765321-7973-4453-8749-472f1ff723e8">

The request:

`<OJP version="2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.vdv.de/ojp" xmlns:siri="http://www.siri.org.uk/siri">
    <OJPRequest>
        <siri:ServiceRequest>
            <siri:RequestTimestamp>2024-08-19T14:35:35Z</siri:RequestTimestamp>
            <siri:RequestorRef>OJP_Demo_iOS_IOS_SDK_0.1.0</siri:RequestorRef>
            <OJPTripRequest>
                <siri:RequestTimestamp>2024-08-19T14:35:35Z</siri:RequestTimestamp>
                <Origin>
                    <PlaceRef>
                        <GeoPosition>
                            <siri:Longitude>7.45183</siri:Longitude>
                            <siri:Latitude>46.95326</siri:Latitude>
                        </GeoPosition>
                        <Name>
                            <Text>Bern, Humboldtstrasse 41</Text>
                        </Name>
                    </PlaceRef>
                    <DepArrTime>2024-08-19T14:35:35Z</DepArrTime>
                </Origin>
                <Destination>
                    <PlaceRef>
                        <StopPlaceRef>22</StopPlaceRef>
                        <Name>
                            <Text>Basel</Text>
                        </Name>
                    </PlaceRef>
                </Destination>
                <Params>
                    <NumberOfResults>6</NumberOfResults>
                    <IncludeIntermediateStops>true</IncludeIntermediateStops>
                    <UseRealtimeData>explanatory</UseRealtimeData>
                </Params>
            </OJPTripRequest>
        </siri:ServiceRequest>
    </OJPRequest>
</OJP>`

**Comment by Flurin-BLS** [comment]
Can also be tested here: https://tools.odpch.ch/ojp-demo-v2/search?from=46.953260,7.451830(Humboldtstrasse%2041%20(Bern))&to=8507492&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-07-25%2007:52&stage=v2-test

![Image](https://github.com/user-attachments/assets/99a84323-dee2-47ce-b69e-abc7665e1fba)

**Comment by Flurin-BLS** [comment]
Hi @TO-mdv - I have assigned this blocker to you... there are two weired things... 

1. why does the routing suggest to walk? -> there is Bus 10 and Tram 9 running every other minute
2. if the walking part would make sense - it would have to be combined with the walk from `Bern Bahnhof` to `Bern`

**Comment by Flurin-BLS** [comment]
Same request works on OJP 1.0 - still suggests to walk, which doesn't make sense: https://opentdatach.github.io/ojp-demo-app/search?from=47.125610,9.458540(Gramsegg%20(Sevelen))&to=8503000&mode_types=monomodal&transport_modes=walk&trip_datetime=2024-08-20%2015:02&stage=prod


![Image](https://github.com/user-attachments/assets/ddde6467-17f5-43d5-a0ac-9aa6901ad06c)

**Comment by TO-mdv** [comment]
Bug already created: [SH-3467](https://youtrack.mentz.net/issue/SH-3467) OJP2.0 TR liefert überflüssiges TransferLeg
Test ongoing

**Comment by Flurin-BLS** [comment]
2) works on TEST-Enviroment, but not on INT and PROD yet..
1) not yet answered...

**Comment by TO-mdv** [comment]
fixed on TEST, release for INT on-going. Also the footpath from Address to Bern is correct now (without deviation via Bern, Bahnhof)


![Image](https://github.com/user-attachments/assets/e9a872f2-9898-4002-b48c-e3ed5d05fbf6)

**Comment by Flurin-BLS** [comment]
Thanks for the update @TO-mdv  - is it due to this update that PROD and INT don't deliver any results right now?
https://tools.odpch.ch/ojp-demo-v2/search?from=46.953260,7.451830(Humboldtstrasse%2041%20(Bern)&to=8507492&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-07-25%2007:52&stage=v2-int

**Comment by Flurin-BLS** [comment]
Good morning @TO-mdv - is it because of this fix that on INT and PROD I don't get any reusults from my address?
https://tools.odpch.ch/ojp-demo-v2/search?from=46.953260,7.451830(Humboldtstrasse%2041%20(Bern)&to=8507492&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-07-25%2007:52&stage=v2-int
On iOS the request takes very long and than "no results" 

![Image](https://github.com/user-attachments/assets/48497a88-3f8c-4cb3-a425-245cf95a307e)


BUT my Adress to Sägemattstrasse 2 Köniz always works... 



![Image](https://github.com/user-attachments/assets/489cca09-adf1-4de6-9a9a-a5a45ad0b834)

**Comment by terencebls** [comment]
fixed
